/* kiconf - Energia tab: night light schedule.
 * See kiconf.c's top doc comment for the overall design.
 *
 * Writes $XDG_CONFIG_HOME/kiconfd-nightlight.conf, the same file
 * xisserve's --energy page writes (its checkbox+slider there is the
 * "manual, right now" side of this feature -- see xisserve/PROTOCOL.md's
 * `--energy` entry). This tab is the only place the schedule itself
 * (start/end/temperature) is set; kiconfd is the only thing that reads
 * it back and applies it, at the configured times, via `xsct`
 * (https://github.com/faf0/sct) -- see kiconfd.c's own doc comment for
 * the daemon side.
 *
 * Gated on `xsct` being installed, same have_cmd()-and-status-label
 * pattern sistema.c uses for localectl/timedatectl: the tab still opens
 * and shows the schedule (so a config made before installing xsct isn't
 * lost), but Aplicar is disabled and a message explains why.
 */
#include "../common.h"
#include "../tabs.h"

#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define NIGHTLIGHT_TEMP_MIN 2700
#define NIGHTLIGHT_TEMP_MAX 6500
#define NIGHTLIGHT_TEMP_DEFAULT 4000

static GtkWidget *g_status_label;
static GtkWidget *g_enabled_chk;
static GtkWidget *g_start_hour_spin, *g_start_min_spin;
static GtkWidget *g_end_hour_spin, *g_end_min_spin;
static GtkWidget *g_temp_spin;

typedef struct {
    int enabled;
    char start[8];
    char end[8];
    int temp;
} NightlightConfig;

static int have_cmd(const char *name)
{
    char out[PATH_MAX];
    char *argv[] = {"which", (char *)name, NULL};
    return run_capture(argv, out, sizeof(out)) && out[0];
}

static void nightlight_defaults(NightlightConfig *c)
{
    c->enabled = 0;
    snprintf(c->start, sizeof(c->start), "20:00");
    snprintf(c->end, sizeof(c->end), "06:00");
    c->temp = NIGHTLIGHT_TEMP_DEFAULT;
}

static void nightlight_load(NightlightConfig *c)
{
    nightlight_defaults(c);
    char path[PATH_MAX];
    resolve_path("kiconfd-nightlight.conf", path, sizeof(path));
    FILE *f = fopen(path, "r");
    if (!f) {
        return;
    }
    char line[128];
    while (fgets(line, sizeof(line), f)) {
        char *l = trim(line);
        if (!*l || *l == '#') {
            continue;
        }
        char *eq = strchr(l, '=');
        if (!eq) {
            continue;
        }
        *eq = '\0';
        char *key = trim(l);
        char *val = trim(eq + 1);
        if (!strcmp(key, "enabled")) {
            c->enabled = atoi(val) ? 1 : 0;
        } else if (!strcmp(key, "start")) {
            snprintf(c->start, sizeof(c->start), "%s", val);
        } else if (!strcmp(key, "end")) {
            snprintf(c->end, sizeof(c->end), "%s", val);
        } else if (!strcmp(key, "temp")) {
            c->temp = atoi(val);
        }
    }
    fclose(f);
}

static void nightlight_save(const NightlightConfig *c)
{
    char path[PATH_MAX];
    resolve_path("kiconfd-nightlight.conf", path, sizeof(path));
    char tmp[PATH_MAX];
    snprintf(tmp, sizeof(tmp), "%s.tmp", path);
    FILE *f = fopen(tmp, "w");
    if (!f) {
        g_warning("kiconf: could not write '%s': %s", tmp, strerror(errno));
        return;
    }
    fprintf(f, "# kiconfd night light schedule -- generated by kiconf's Energia tab,\n");
    fprintf(f, "# applied via xsct by kiconfd. xisserve's --energy page can also flip\n");
    fprintf(f, "# 'enabled' (its checkbox) and 'temp' (its slider, when not automatic).\n");
    fprintf(f, "enabled = %d\n", c->enabled);
    fprintf(f, "start = %s\n", c->start);
    fprintf(f, "end = %s\n", c->end);
    fprintf(f, "temp = %d\n", c->temp);
    fclose(f);
    if (rename(tmp, path) != 0) {
        g_warning("kiconf: could not save '%s': %s", path, strerror(errno));
    }
}

/* "HH:MM" -> two spin buttons. Malformed/out-of-range values fall back
 * to 0:00 rather than rejecting the whole config over one bad field. */
static void set_time_spins(const char *hhmm, GtkWidget *hour_spin, GtkWidget *min_spin)
{
    int h = 0, m = 0;
    sscanf(hhmm, "%d:%d", &h, &m);
    if (h < 0 || h > 23) {
        h = 0;
    }
    if (m < 0 || m > 59) {
        m = 0;
    }
    gtk_spin_button_set_value(GTK_SPIN_BUTTON(hour_spin), h);
    gtk_spin_button_set_value(GTK_SPIN_BUTTON(min_spin), m);
}

static void get_time_spins(char *out, size_t outsz, GtkWidget *hour_spin, GtkWidget *min_spin)
{
    snprintf(out, outsz, "%02d:%02d",
             gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(hour_spin)),
             gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(min_spin)));
}

static void apply_cb(GtkWidget *widget, gpointer data)
{
    (void)widget;
    (void)data;

    NightlightConfig c;
    c.enabled = gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(g_enabled_chk));
    get_time_spins(c.start, sizeof(c.start), g_start_hour_spin, g_start_min_spin);
    get_time_spins(c.end, sizeof(c.end), g_end_hour_spin, g_end_min_spin);
    c.temp = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(g_temp_spin));

    nightlight_save(&c);
    signal_daemon("kiconfd");
    gtk_label_set_text(GTK_LABEL(g_status_label), _("Horario de luz noturna salvo."));
}

GtkWidget *build_energia_tab(void)
{
    GtkWidget *outer = gtk_vbox_new(FALSE, 8);
    gtk_container_set_border_width(GTK_CONTAINER(outer), 12);

    int have_xsct = have_cmd("xsct");

    g_status_label = gtk_label_new(have_xsct ? ""
        : _("xsct nao encontrado -- instale-o (https://github.com/faf0/sct) para "
            "a luz noturna automatica funcionar. O horario ainda pode ser configurado "
            "e salvo aqui."));
    gtk_misc_set_alignment(GTK_MISC(g_status_label), 0.0, 0.5);
    gtk_label_set_line_wrap(GTK_LABEL(g_status_label), TRUE);
    gtk_box_pack_start(GTK_BOX(outer), g_status_label, FALSE, FALSE, 0);

    NightlightConfig c;
    nightlight_load(&c);

    GtkWidget *box = gtk_vbox_new(FALSE, 6);

    g_enabled_chk = gtk_check_button_new_with_label(_("Ativar luz noturna automatica"));
    gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(g_enabled_chk), c.enabled);
    gtk_box_pack_start(GTK_BOX(box), g_enabled_chk, FALSE, FALSE, 0);

    GtkWidget *sched_box = gtk_hbox_new(FALSE, 4);
    gtk_box_pack_start(GTK_BOX(sched_box), gtk_label_new(_("Ligar as:")), FALSE, FALSE, 0);
    g_start_hour_spin = gtk_spin_button_new_with_range(0, 23, 1);
    g_start_min_spin = gtk_spin_button_new_with_range(0, 59, 1);
    gtk_box_pack_start(GTK_BOX(sched_box), g_start_hour_spin, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(sched_box), gtk_label_new(":"), FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(sched_box), g_start_min_spin, FALSE, FALSE, 0);

    gtk_box_pack_start(GTK_BOX(sched_box), gtk_label_new(_("   Desligar as:")), FALSE, FALSE, 0);
    g_end_hour_spin = gtk_spin_button_new_with_range(0, 23, 1);
    g_end_min_spin = gtk_spin_button_new_with_range(0, 59, 1);
    gtk_box_pack_start(GTK_BOX(sched_box), g_end_hour_spin, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(sched_box), gtk_label_new(":"), FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(sched_box), g_end_min_spin, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(box), sched_box, FALSE, FALSE, 0);
    set_time_spins(c.start, g_start_hour_spin, g_start_min_spin);
    set_time_spins(c.end, g_end_hour_spin, g_end_min_spin);

    GtkWidget *temp_table = gtk_table_new(1, 2, FALSE);
    g_temp_spin = gtk_spin_button_new_with_range(NIGHTLIGHT_TEMP_MIN, NIGHTLIGHT_TEMP_MAX, 100);
    gtk_spin_button_set_value(GTK_SPIN_BUTTON(g_temp_spin), c.temp);
    labeled_row(temp_table, 0, _("Temperatura durante o periodo (K):"), g_temp_spin);
    gtk_box_pack_start(GTK_BOX(box), temp_table, FALSE, FALSE, 0);

    gtk_box_pack_start(GTK_BOX(outer),
                        frame_with(_("Luz noturna (xsct)"), box), FALSE, FALSE, 0);

    GtkWidget *note = gtk_label_new(
        _("Fora do horario configurado, a tela volta a temperatura normal. "
          "Um horario de desligar menor que o de ligar cruza a meia-noite "
          "(ex.: ligar 20:00, desligar 06:00)."));
    gtk_misc_set_alignment(GTK_MISC(note), 0.0, 0.5);
    gtk_label_set_line_wrap(GTK_LABEL(note), TRUE);
    gtk_box_pack_start(GTK_BOX(outer), note, FALSE, FALSE, 0);

    GtkWidget *btnbox = gtk_hbox_new(FALSE, 0);
    GtkWidget *apply_btn = gtk_button_new_with_label(_("Aplicar"));
    g_signal_connect(apply_btn, "clicked", G_CALLBACK(apply_cb), NULL);
    gtk_box_pack_end(GTK_BOX(btnbox), apply_btn, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(outer), btnbox, FALSE, FALSE, 0);

    return outer;
}
