/* kiconf - Historico tab: kistory.conf and kimemory.conf.
 * See kiconf.c's top doc comment for the overall design.
 *
 * Both daemons read $XDG_CONFIG_HOME/<name>.conf directly (key=value,
 * SIGHUP reloads) and have no control socket for settings -- kimemoryd's
 * control socket (see kimemory/README.md) only serves runtime queries
 * (LIST/GET/PASTE/...), and kistoryd has none yet. So this tab edits the
 * conf files the same way the Energia tab edits kiconfd-nightlight.conf,
 * instead of going over a socket like the Permissoes tab does for
 * xisguard. "Espaco em disco" and "Limpar" shell out to the `kistory`/
 * `kimemory` CLIs (stats/purge, status/clear), which already do this
 * correctly (atomic rewrite, flock) -- reimplementing that here would
 * just be a second, divergent copy of the same logic.
 */
#include "../common.h"
#include "../tabs.h"

#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static GtkWidget *g_ks_dwell_spin, *g_ks_retention_spin, *g_ks_fd_sampling_chk;
static GtkWidget *g_ks_exclude_entry, *g_ks_title_only_entry, *g_ks_private_regex_entry;
static GtkWidget *g_ks_guard_actions_entry;
static GtkWidget *g_ks_stats_label;

static const char *const KM_PERSIST_OPTS[] = {"all", "favorites", "none", NULL};
static const char *const KM_TAKEOVER_OPTS[] = {"simple", "onexit", "never", NULL};
static GtkWidget *g_km_max_entries_spin, *g_km_persist_combo, *g_km_takeover_combo;
static GtkWidget *g_km_exclude_entry, *g_km_never_takeover_entry;
static GtkWidget *g_km_max_text_spin, *g_km_max_image_spin, *g_km_max_mirror_spin;
static GtkWidget *g_km_stats_label;

typedef struct {
    int min_dwell_s;
    int retention_days;
    int fd_sampling;
    char exclude[256];
    char title_only_exclude[256];
    char private_title_regex[256];
    char guard_actions[128];
} KistoryConfig;

typedef struct {
    int max_entries;
    char persist[16];
    char takeover[16];
    char exclude[256];
    char never_takeover[256];
    int max_text_kb;
    int max_image_mb;
    int max_mirror_mb;
} KimemoryConfig;

/* Shared by both configs: trimmed "key = value" or "key=value" lines,
 * '#' comments, blank lines skipped. Matches kistoryd/kimemoryd's own
 * loader (see their READMEs' Config tables). */
static void conf_load_kv(const char *filename, void (*set)(void *c, const char *key, const char *val), void *c)
{
    char path[PATH_MAX];
    resolve_path(filename, path, sizeof(path));
    FILE *f = fopen(path, "r");
    if (!f) {
        return;
    }
    char line[512];
    while (fgets(line, sizeof(line), f)) {
        char *l = trim(line);
        if (!*l || *l == '#') {
            continue;
        }
        char *eq = strchr(l, '=');
        if (!eq) {
            continue;
        }
        *eq = '\0';
        char *key = trim(l);
        char *val = trim(eq + 1);
        set(c, key, val);
    }
    fclose(f);
}

static void kistory_defaults(KistoryConfig *c)
{
    memset(c, 0, sizeof(*c));
    c->min_dwell_s = 3;
    c->retention_days = 90;
    c->fd_sampling = 1;
    snprintf(c->exclude, sizeof(c->exclude), "keepassxc,KeePassXC");
    snprintf(c->guard_actions, sizeof(c->guard_actions), "SCREEN,RECORD,INPUT_INJECT,INPUT");
}

static void kistory_set_kv(void *vc, const char *key, const char *val)
{
    KistoryConfig *c = vc;
    if (!strcmp(key, "min_dwell_s")) {
        c->min_dwell_s = atoi(val);
    } else if (!strcmp(key, "retention_days")) {
        c->retention_days = atoi(val);
    } else if (!strcmp(key, "fd_sampling")) {
        c->fd_sampling = atoi(val) != 0;
    } else if (!strcmp(key, "exclude")) {
        snprintf(c->exclude, sizeof(c->exclude), "%s", val);
    } else if (!strcmp(key, "title_only_exclude")) {
        snprintf(c->title_only_exclude, sizeof(c->title_only_exclude), "%s", val);
    } else if (!strcmp(key, "private_title_regex")) {
        snprintf(c->private_title_regex, sizeof(c->private_title_regex), "%s", val);
    } else if (!strcmp(key, "guard_actions")) {
        snprintf(c->guard_actions, sizeof(c->guard_actions), "%s", val);
    }
}

static void kistory_load(KistoryConfig *c)
{
    kistory_defaults(c);
    conf_load_kv("kistory.conf", kistory_set_kv, c);
}

static void kistory_save(const KistoryConfig *c)
{
    char path[PATH_MAX];
    resolve_path("kistory.conf", path, sizeof(path));
    char tmp[PATH_MAX];
    snprintf(tmp, sizeof(tmp), "%s.tmp", path);
    FILE *f = fopen(tmp, "w");
    if (!f) {
        g_warning("kiconf: could not write '%s': %s", tmp, strerror(errno));
        return;
    }
    fprintf(f, "# kistory config -- generated by kiconf's Historico tab.\n");
    fprintf(f, "# See kistory/README.md for what each key does.\n");
    fprintf(f, "min_dwell_s=%d\n", c->min_dwell_s);
    fprintf(f, "retention_days=%d\n", c->retention_days);
    fprintf(f, "fd_sampling=%d\n", c->fd_sampling);
    fprintf(f, "exclude=%s\n", c->exclude);
    fprintf(f, "title_only_exclude=%s\n", c->title_only_exclude);
    fprintf(f, "private_title_regex=%s\n", c->private_title_regex);
    fprintf(f, "guard_actions=%s\n", c->guard_actions);
    fclose(f);
    if (rename(tmp, path) != 0) {
        g_warning("kiconf: could not save '%s': %s", path, strerror(errno));
    }
}

static void kimemory_defaults(KimemoryConfig *c)
{
    memset(c, 0, sizeof(*c));
    c->max_entries = 200;
    snprintf(c->persist, sizeof(c->persist), "all");
    snprintf(c->takeover, sizeof(c->takeover), "simple");
    snprintf(c->exclude, sizeof(c->exclude), "keepassxc,KeePassXC");
    snprintf(c->never_takeover, sizeof(c->never_takeover),
             "libreoffice,soffice,gimp,krita,inkscape,blender");
    c->max_text_kb = 1024;
    c->max_image_mb = 20;
    c->max_mirror_mb = 4;
}

static void kimemory_set_kv(void *vc, const char *key, const char *val)
{
    KimemoryConfig *c = vc;
    if (!strcmp(key, "max_entries")) {
        c->max_entries = atoi(val);
    } else if (!strcmp(key, "persist")) {
        snprintf(c->persist, sizeof(c->persist), "%s", val);
    } else if (!strcmp(key, "takeover")) {
        snprintf(c->takeover, sizeof(c->takeover), "%s", val);
    } else if (!strcmp(key, "exclude")) {
        snprintf(c->exclude, sizeof(c->exclude), "%s", val);
    } else if (!strcmp(key, "never_takeover")) {
        snprintf(c->never_takeover, sizeof(c->never_takeover), "%s", val);
    } else if (!strcmp(key, "max_text_kb")) {
        c->max_text_kb = atoi(val);
    } else if (!strcmp(key, "max_image_mb")) {
        c->max_image_mb = atoi(val);
    } else if (!strcmp(key, "max_mirror_mb")) {
        c->max_mirror_mb = atoi(val);
    }
}

static void kimemory_load(KimemoryConfig *c)
{
    kimemory_defaults(c);
    conf_load_kv("kimemory.conf", kimemory_set_kv, c);
}

static void kimemory_save(const KimemoryConfig *c)
{
    char path[PATH_MAX];
    resolve_path("kimemory.conf", path, sizeof(path));
    char tmp[PATH_MAX];
    snprintf(tmp, sizeof(tmp), "%s.tmp", path);
    FILE *f = fopen(tmp, "w");
    if (!f) {
        g_warning("kiconf: could not write '%s': %s", tmp, strerror(errno));
        return;
    }
    fprintf(f, "# kimemory config -- generated by kiconf's Historico tab.\n");
    fprintf(f, "# See kimemory/README.md for what each key does.\n");
    fprintf(f, "max_entries=%d\n", c->max_entries);
    fprintf(f, "persist=%s\n", c->persist);
    fprintf(f, "takeover=%s\n", c->takeover);
    fprintf(f, "exclude=%s\n", c->exclude);
    fprintf(f, "never_takeover=%s\n", c->never_takeover);
    fprintf(f, "max_text_kb=%d\n", c->max_text_kb);
    fprintf(f, "max_image_mb=%d\n", c->max_image_mb);
    fprintf(f, "max_mirror_mb=%d\n", c->max_mirror_mb);
    fclose(f);
    if (rename(tmp, path) != 0) {
        g_warning("kiconf: could not save '%s': %s", path, strerror(errno));
    }
}

static void apply_kistory_cb(GtkWidget *widget, gpointer data)
{
    (void)widget;
    (void)data;
    KistoryConfig c;
    kistory_defaults(&c);
    c.min_dwell_s = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(g_ks_dwell_spin));
    c.retention_days = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(g_ks_retention_spin));
    c.fd_sampling = gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(g_ks_fd_sampling_chk));
    snprintf(c.exclude, sizeof(c.exclude), "%s", gtk_entry_get_text(GTK_ENTRY(g_ks_exclude_entry)));
    snprintf(c.title_only_exclude, sizeof(c.title_only_exclude), "%s",
             gtk_entry_get_text(GTK_ENTRY(g_ks_title_only_entry)));
    snprintf(c.private_title_regex, sizeof(c.private_title_regex), "%s",
             gtk_entry_get_text(GTK_ENTRY(g_ks_private_regex_entry)));
    snprintf(c.guard_actions, sizeof(c.guard_actions), "%s",
             gtk_entry_get_text(GTK_ENTRY(g_ks_guard_actions_entry)));
    kistory_save(&c);
    signal_daemon("kistoryd");
}

static void apply_kimemory_cb(GtkWidget *widget, gpointer data)
{
    (void)widget;
    (void)data;
    KimemoryConfig c;
    kimemory_defaults(&c);
    c.max_entries = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(g_km_max_entries_spin));
    snprintf(c.persist, sizeof(c.persist), "%s", combo_text(g_km_persist_combo, KM_PERSIST_OPTS));
    snprintf(c.takeover, sizeof(c.takeover), "%s", combo_text(g_km_takeover_combo, KM_TAKEOVER_OPTS));
    snprintf(c.exclude, sizeof(c.exclude), "%s", gtk_entry_get_text(GTK_ENTRY(g_km_exclude_entry)));
    snprintf(c.never_takeover, sizeof(c.never_takeover), "%s",
             gtk_entry_get_text(GTK_ENTRY(g_km_never_takeover_entry)));
    c.max_text_kb = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(g_km_max_text_spin));
    c.max_image_mb = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(g_km_max_image_spin));
    c.max_mirror_mb = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(g_km_max_mirror_spin));
    kimemory_save(&c);
    signal_daemon("kimemoryd");
}

static void on_kistory_stats(GtkWidget *widget, gpointer data)
{
    (void)widget;
    (void)data;
    char out[2048];
    char *argv[] = {"kistory", "stats", NULL};
    if (run_capture(argv, out, sizeof(out)) && out[0]) {
        gtk_label_set_text(GTK_LABEL(g_ks_stats_label), trim(out));
    } else {
        gtk_label_set_text(GTK_LABEL(g_ks_stats_label), _("kistory nao encontrado, ou kistoryd parado sem historico ainda gravado."));
    }
}

static void on_kistory_purge(GtkWidget *widget, gpointer data)
{
    (void)widget;
    (void)data;
    GtkWidget *dlg = gtk_message_dialog_new(NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING,
        GTK_BUTTONS_YES_NO, "%s",
        _("Apagar todo o historico de atividade do kistory? Isso nao pode ser desfeito."));
    int resp = gtk_dialog_run(GTK_DIALOG(dlg));
    gtk_widget_destroy(dlg);
    if (resp != GTK_RESPONSE_YES) {
        return;
    }
    char out[256];
    char *argv[] = {"kistory", "purge", "--all", NULL};
    run_capture(argv, out, sizeof(out));
    on_kistory_stats(NULL, NULL);
}

static void on_kimemory_stats(GtkWidget *widget, gpointer data)
{
    (void)widget;
    (void)data;
    char out[2048];
    char *argv[] = {"kimemory", "status", NULL};
    if (run_capture(argv, out, sizeof(out)) && out[0]) {
        gtk_label_set_text(GTK_LABEL(g_km_stats_label), trim(out));
    } else {
        gtk_label_set_text(GTK_LABEL(g_km_stats_label), _("kimemory nao encontrado, ou kimemoryd nao esta rodando (status precisa do daemon)."));
    }
}

static void on_kimemory_clear(GtkWidget *widget, gpointer data)
{
    (void)widget;
    (void)data;
    GtkWidget *dlg = gtk_message_dialog_new(NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING,
        GTK_BUTTONS_YES_NO, "%s",
        _("Apagar todo o historico de area de transferencia, inclusive favoritos? Isso nao pode ser desfeito."));
    int resp = gtk_dialog_run(GTK_DIALOG(dlg));
    gtk_widget_destroy(dlg);
    if (resp != GTK_RESPONSE_YES) {
        return;
    }
    char out[256];
    char *argv[] = {"kimemory", "clear", "--all", NULL};
    run_capture(argv, out, sizeof(out));
    on_kimemory_stats(NULL, NULL);
}

GtkWidget *build_historico_tab(void)
{
    GtkWidget *outer = gtk_vbox_new(FALSE, 8);
    gtk_container_set_border_width(GTK_CONTAINER(outer), 12);

    GtkWidget *note = gtk_label_new(
        _("kistory (atividade: janelas, foco, arquivos, audio) e kimemory "
          "(area de transferencia) guardam tudo em texto, sem capturas de "
          "tela. Ligar/desligar os daemons fica na aba Iniciar automaticamente."));
    gtk_misc_set_alignment(GTK_MISC(note), 0.0, 0.5);
    gtk_label_set_line_wrap(GTK_LABEL(note), TRUE);
    gtk_box_pack_start(GTK_BOX(outer), note, FALSE, FALSE, 0);

    GtkWidget *cols = gtk_hbox_new(FALSE, 8);

    /* ---- kistory column -------------------------------------------- */
    KistoryConfig ksc;
    kistory_load(&ksc);

    GtkWidget *ks_box = gtk_vbox_new(FALSE, 6);
    GtkWidget *ks_table = gtk_table_new(4, 2, FALSE);
    g_ks_dwell_spin = gtk_spin_button_new_with_range(0, 3600, 1);
    gtk_spin_button_set_value(GTK_SPIN_BUTTON(g_ks_dwell_spin), ksc.min_dwell_s);
    labeled_row(ks_table, 0, _("Permanencia minima p/ registrar foco (s):"), g_ks_dwell_spin);
    g_ks_retention_spin = gtk_spin_button_new_with_range(0, 3650, 1);
    gtk_spin_button_set_value(GTK_SPIN_BUTTON(g_ks_retention_spin), ksc.retention_days);
    gtk_widget_set_tooltip_text(g_ks_retention_spin, _("0 = guardar para sempre"));
    labeled_row(ks_table, 1, _("Reter historico por (dias):"), g_ks_retention_spin);
    g_ks_guard_actions_entry = gtk_entry_new();
    gtk_entry_set_text(GTK_ENTRY(g_ks_guard_actions_entry), ksc.guard_actions);
    gtk_widget_set_tooltip_text(g_ks_guard_actions_entry,
        _("Acoes do xisguard a registrar, separadas por virgula. Vazio: nao assina."));
    labeled_row(ks_table, 2, _("Acoes do xisguard a registrar:"), g_ks_guard_actions_entry);
    g_ks_fd_sampling_chk = gtk_check_button_new_with_label(
        _("Registrar arquivos abertos por programas (alem do recentes)"));
    gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(g_ks_fd_sampling_chk), ksc.fd_sampling);
    gtk_table_attach(GTK_TABLE(ks_table), g_ks_fd_sampling_chk, 0, 2, 3, 4, GTK_FILL, GTK_FILL, 4, 3);
    gtk_box_pack_start(GTK_BOX(ks_box), ks_table, FALSE, FALSE, 0);

    g_ks_exclude_entry = gtk_entry_new();
    gtk_entry_set_text(GTK_ENTRY(g_ks_exclude_entry), ksc.exclude);
    gtk_widget_set_tooltip_text(g_ks_exclude_entry,
        _("Classes/nomes de programas nunca registrados, separados por virgula."));
    GtkWidget *ks_table2 = gtk_table_new(2, 2, FALSE);
    labeled_row(ks_table2, 0, _("Nunca registrar:"), g_ks_exclude_entry);
    g_ks_title_only_entry = gtk_entry_new();
    gtk_entry_set_text(GTK_ENTRY(g_ks_title_only_entry), ksc.title_only_exclude);
    gtk_widget_set_tooltip_text(g_ks_title_only_entry,
        _("Registrados sem titulo (so app, horario e local)."));
    labeled_row(ks_table2, 1, _("Registrar sem titulo:"), g_ks_title_only_entry);
    gtk_box_pack_start(GTK_BOX(ks_box), ks_table2, FALSE, FALSE, 0);

    GtkWidget *ks_table3 = gtk_table_new(1, 2, FALSE);
    g_ks_private_regex_entry = gtk_entry_new();
    gtk_entry_set_text(GTK_ENTRY(g_ks_private_regex_entry), ksc.private_title_regex);
    gtk_widget_set_tooltip_text(g_ks_private_regex_entry,
        _("Regex (POSIX estendida); titulos de janela anonima/privada que baterem ficam sem titulo. Vazio por padrao."));
    labeled_row(ks_table3, 0, _("Titulo privado (regex):"), g_ks_private_regex_entry);
    gtk_box_pack_start(GTK_BOX(ks_box), ks_table3, FALSE, FALSE, 0);

    GtkWidget *ks_apply_row = gtk_hbox_new(FALSE, 0);
    GtkWidget *ks_apply_btn = gtk_button_new_with_label(_("Aplicar"));
    g_signal_connect(ks_apply_btn, "clicked", G_CALLBACK(apply_kistory_cb), NULL);
    gtk_box_pack_end(GTK_BOX(ks_apply_row), ks_apply_btn, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(ks_box), ks_apply_row, FALSE, FALSE, 0);

    GtkWidget *ks_space_box = gtk_vbox_new(FALSE, 4);
    g_ks_stats_label = gtk_label_new("-");
    gtk_misc_set_alignment(GTK_MISC(g_ks_stats_label), 0.0, 0.5);
    gtk_label_set_line_wrap(GTK_LABEL(g_ks_stats_label), TRUE);
    gtk_box_pack_start(GTK_BOX(ks_space_box), g_ks_stats_label, FALSE, FALSE, 0);
    GtkWidget *ks_space_btns = gtk_hbox_new(FALSE, 6);
    GtkWidget *ks_stats_btn = gtk_button_new_with_label(_("Ver espaco usado"));
    GtkWidget *ks_purge_btn = gtk_button_new_with_label(_("Limpar tudo"));
    g_signal_connect(ks_stats_btn, "clicked", G_CALLBACK(on_kistory_stats), NULL);
    g_signal_connect(ks_purge_btn, "clicked", G_CALLBACK(on_kistory_purge), NULL);
    gtk_box_pack_start(GTK_BOX(ks_space_btns), ks_stats_btn, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(ks_space_btns), ks_purge_btn, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(ks_space_box), ks_space_btns, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(ks_box), frame_with(_("Espaco em disco"), ks_space_box), FALSE, FALSE, 0);

    gtk_box_pack_start(GTK_BOX(cols), frame_with(_("kistory (atividade)"), ks_box), TRUE, TRUE, 0);

    /* ---- kimemory column -------------------------------------------- */
    KimemoryConfig kmc;
    kimemory_load(&kmc);

    GtkWidget *km_box = gtk_vbox_new(FALSE, 6);
    GtkWidget *km_table = gtk_table_new(6, 2, FALSE);
    g_km_max_entries_spin = gtk_spin_button_new_with_range(1, 100000, 10);
    gtk_spin_button_set_value(GTK_SPIN_BUTTON(g_km_max_entries_spin), kmc.max_entries);
    gtk_widget_set_tooltip_text(g_km_max_entries_spin, _("Favoritos nao contam no limite."));
    labeled_row(km_table, 0, _("Maximo de itens:"), g_km_max_entries_spin);
    g_km_persist_combo = make_options_combo(KM_PERSIST_OPTS, kmc.persist);
    gtk_widget_set_tooltip_text(g_km_persist_combo,
        _("all: tudo em disco. favorites: so favoritos; o resto fica so em RAM. none: nada."));
    labeled_row(km_table, 1, _("Guardar no disco:"), g_km_persist_combo);
    g_km_takeover_combo = make_options_combo(KM_TAKEOVER_OPTS, kmc.takeover);
    gtk_widget_set_tooltip_text(g_km_takeover_combo,
        _("simple: assume copias simples na hora. onexit: so quando o app fecha. never: nunca assume."));
    labeled_row(km_table, 2, _("Assumir a area de transferencia:"), g_km_takeover_combo);
    g_km_max_text_spin = gtk_spin_button_new_with_range(1, 1048576, 64);
    gtk_spin_button_set_value(GTK_SPIN_BUTTON(g_km_max_text_spin), kmc.max_text_kb);
    labeled_row(km_table, 3, _("Texto maximo (KB):"), g_km_max_text_spin);
    g_km_max_image_spin = gtk_spin_button_new_with_range(1, 1024, 1);
    gtk_spin_button_set_value(GTK_SPIN_BUTTON(g_km_max_image_spin), kmc.max_image_mb);
    labeled_row(km_table, 4, _("Imagem maxima (MB):"), g_km_max_image_spin);
    g_km_max_mirror_spin = gtk_spin_button_new_with_range(1, 1024, 1);
    gtk_spin_button_set_value(GTK_SPIN_BUTTON(g_km_max_mirror_spin), kmc.max_mirror_mb);
    gtk_widget_set_tooltip_text(g_km_max_mirror_spin,
        _("Limite extra para os outros formatos espelhados de uma copia simples."));
    labeled_row(km_table, 5, _("Espelhamento extra (MB):"), g_km_max_mirror_spin);
    gtk_box_pack_start(GTK_BOX(km_box), km_table, FALSE, FALSE, 0);

    GtkWidget *km_table2 = gtk_table_new(2, 2, FALSE);
    g_km_exclude_entry = gtk_entry_new();
    gtk_entry_set_text(GTK_ENTRY(g_km_exclude_entry), kmc.exclude);
    gtk_widget_set_tooltip_text(g_km_exclude_entry,
        _("Classes/nomes de programas cujas copias nunca sao registradas, separados por virgula."));
    labeled_row(km_table2, 0, _("Nunca registrar:"), g_km_exclude_entry);
    g_km_never_takeover_entry = gtk_entry_new();
    gtk_entry_set_text(GTK_ENTRY(g_km_never_takeover_entry), kmc.never_takeover);
    gtk_widget_set_tooltip_text(g_km_never_takeover_entry,
        _("Programas sempre tratados como copia rica (nao assumida enquanto o app estiver aberto)."));
    labeled_row(km_table2, 1, _("Sempre rica (app aberto):"), g_km_never_takeover_entry);
    gtk_box_pack_start(GTK_BOX(km_box), km_table2, FALSE, FALSE, 0);

    GtkWidget *km_apply_row = gtk_hbox_new(FALSE, 0);
    GtkWidget *km_apply_btn = gtk_button_new_with_label(_("Aplicar"));
    g_signal_connect(km_apply_btn, "clicked", G_CALLBACK(apply_kimemory_cb), NULL);
    gtk_box_pack_end(GTK_BOX(km_apply_row), km_apply_btn, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(km_box), km_apply_row, FALSE, FALSE, 0);

    GtkWidget *km_space_box = gtk_vbox_new(FALSE, 4);
    g_km_stats_label = gtk_label_new("-");
    gtk_misc_set_alignment(GTK_MISC(g_km_stats_label), 0.0, 0.5);
    gtk_label_set_line_wrap(GTK_LABEL(g_km_stats_label), TRUE);
    gtk_box_pack_start(GTK_BOX(km_space_box), g_km_stats_label, FALSE, FALSE, 0);
    GtkWidget *km_space_btns = gtk_hbox_new(FALSE, 6);
    GtkWidget *km_stats_btn = gtk_button_new_with_label(_("Ver estado"));
    GtkWidget *km_clear_btn = gtk_button_new_with_label(_("Limpar tudo"));
    g_signal_connect(km_stats_btn, "clicked", G_CALLBACK(on_kimemory_stats), NULL);
    g_signal_connect(km_clear_btn, "clicked", G_CALLBACK(on_kimemory_clear), NULL);
    gtk_box_pack_start(GTK_BOX(km_space_btns), km_stats_btn, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(km_space_btns), km_clear_btn, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(km_space_box), km_space_btns, FALSE, FALSE, 0);
    gtk_box_pack_start(GTK_BOX(km_box), frame_with(_("Espaco em disco"), km_space_box), FALSE, FALSE, 0);

    gtk_box_pack_start(GTK_BOX(cols), frame_with(_("kimemory (area de transferencia)"), km_box), TRUE, TRUE, 0);

    gtk_box_pack_start(GTK_BOX(outer), cols, TRUE, TRUE, 0);

    return outer;
}
